### ISSUE TITLE
[enhancement] Options: space around delimiter

### ISSUE THREAD

**Issue by alexsasharegan** [Guitarbum722/align#30]
# Spacing Options
- [ ] space around
- [ ] leading space
- [ ] trailing space
- [ ] initial leading space
- [ ] final trailing space

To consider the spacing option, let's use the following input:

```
| Prop | Type | Default | Description |
| :-------: | :-------: | :-------: | ------- |
| tag | String    | `"div"`   | Element tagName _(any valid HTML tag name)_ |
| inline   | Boolean   | `false`   | `display: inline-flex` |
```

## Space Around
Space around would specify the minimum amount of white-space to add before and after a delimiter. In this shortcut option, initial leading space and final trailing space would **not** be included.
```
// space around: 1
| Prop      | Type      | Default   | Description |
| :-------: | :-------: | :-------: |   -------   |
| tag       | String    | `"div"`   | Element tagName _(any valid HTML tag name)_ |
| inline    | Boolean   | `false`   | `display: inline-flex` |
```

## Leading Space
Leading space would only specify the minimum amount of space immediately following a delimiter, excepting an initial delimiter not preceded by content.
```
// leading space: 1
| Prop     | Type     | Default  | Description|
| :-------:| :-------:| :-------:|   -------  |
| tag      | String   | `"div"`  | Element tagName _(any valid HTML tag name)_|
| inline   | Boolean  | `false`  | `display: inline-flex`|
```

## Trailing Space
Trailing space would only specify the minimum amount of space immediately preceding a delimiter, excepting one that is not followed by content.
```
// trailing space: 1
|Prop      |Type      |Default   |Description |
|:-------: |:-------: |:-------: |  -------   |
|tag       |String    |`"div"`   |Element tagName _(any valid HTML tag name)_ |
|inline    |Boolean   |`false`   |`display: inline-flex` |
```

## Initial Leading Space
Specify an amount of space to place before all content

## Final Trailing Space
Specify an amount of space to place after all content

**Comment by Guitarbum722** [comment]
@alexsasharegan -
These are cool suggestions and certainly within reach.  I want to confirm a couple of things just to document it here.

1. In your `Space Around` example above, are you stating that the last column does not necessarily have to be padded to align the final `|`?  That is a practical suggestion in the case of Markdown tables; I just want to confirm the "ask."  So, it would be optional to avoid this? 
```
| Prop      | Type      | Default   | Description                                 |
| :-------: | :-------: | :-------: |   -------                                   |
| tag       | String    | `"div"`   | Element tagName _(any valid HTML tag name)_ |
| inline    | Boolean   | `false`   | `display: inline-flex`                      |
```

And, to confirm the difference between "initial leading space" vs "leading space" you would find it useful to specify the amount of padding following the delimiter AND the amount of padding before the data (following the 'initial leading space')?  This question pertains to the trailing space respectively.

**Comment by alexsasharegan** [comment]
I was making the distinction that `space-around` does not include what's defined `initial-leading-space && final-trailing-space`.
