### ISSUE TITLE
Allow For Numbers to Have Different Alignment

### ISSUE THREAD

**Issue by briandowns** [Guitarbum722/align#39]

**Comment by briandowns** [comment]
This came to mind when thinking about how Excel and others treat numbers differently when the column knows the data type.

**Comment by Guitarbum722** [comment]
I'm up for anything that keeps users out of Excel!  So, for example, a completely numeric column would have the opposite justification than what is specified?
```
First , Last  , CostCenter , ExpenseLine , ExpenseAmt , Date
John  , Moore , 4F         ,           2 ,      33.29 , 5/5/1930
```

**Comment by briandowns** [comment]
Yes, if the user chooses it to be that way or some other justification. I guess maybe this could be achieved automatically and a justification could be chosen programmatically or possibly introduce another flag that indicates the justification for a certain type.  I think likely numeric would be the best candidate so possibly a `-n <justification>`?
