### ISSUE TITLE
Commas Between Quotes Seem to Be Used as Delimeters

### ISSUE THREAD

**Issue by briandowns** [Guitarbum722/align#42]
```
45862 | 12515 | "Midwest Electric                        |  Inc"        | OH           | Bundled               | Cooperative           | 0.0915350239036  | 0.0777018476335 | 0.113463086111
```

**Comment by Guitarbum722** [comment]
Hey @briandowns - 
That is what the `-q` options is for.  Do you still experience this if you specify a double quote as your qualifier `-q \"`?

**Comment by briandowns** [comment]
I hadn't noticed that. My bad. Makes me wonder if there might be a consideration to make that default behavior?

**Comment by Guitarbum722** [comment]
Completely valid point...I guess I considered a lot of import wizards which have you specify a single or double quote if applicable.  I've seen a lot of files with and without the need. 

Do you think it would be practical to leave the flag option there, but default to a double quote?

**Comment by briandowns** [comment]
Meh, leave it as is I guess. This is jus the result of me not reading the instructions first.

**Comment by Guitarbum722** [comment]
Ok.  I'm completely up for revisiting this if some other users bring it up.
