### ISSUE TITLE
Split CLI and aligning code to allow importing as a library

### ISSUE THREAD

**Issue by bradleyjkemp** [Guitarbum722/align#56]
Would be great to be able to import this as a library but currently that isn't possible because everything is package "main"

**Comment by Guitarbum722** [comment]
Thanks for the suggestion.  It's interesting; this started out as a lib and was later changed to be the CLI app only.  

Out of curiosity, what would be a possible use case?

**Comment by bradleyjkemp** [comment]
So if I'm writing something that reads a CSV then it would be useful to import this as a library and use it as a pretty printer (and so not force the user to pipe my unformatted output into another tool)
