### ISSUE TITLE
No Whitespace In Output

### ISSUE THREAD

**Issue by briandowns** [Guitarbum722/align#65]
Is there a way to output the contents of the delimited file with no whitespace characters?

**Comment by Guitarbum722** [comment]
Hey Brian - not sure I know what you mean.  Do you mean the padding?

**Comment by Guitarbum722** [comment]
Oh I see.  Yeah, out of the box it will just consider the space as part of the content and will leave it as it scrapes through each rune.  

However, you might be able to fake it by specifying a padding of `0` with `-p` and an input delimiter that is of comma+space.  So something like this might get you to your destination.
`align -f input.csv -p 0 -s ", " -d ","`

**Comment by briandowns** [comment]
Awesome. I'll give it a try. Thanks!

**Comment by Guitarbum722** [comment]
I suppose that I never considered trimming the whitespace.  Do you encounter the need a lot?  That would be a pretty neat and easy feature to add with a simple boolean flag.

**Comment by briandowns** [comment]
I agree. At least for leading and trailing space, yes.
