### ISSUE TITLE
latest release binary giving error output

### ISSUE THREAD

**Issue by muralikodali** [Guitarbum722/align#75]
v1.1.1 is running well on my Arch Linux machine.

latest release binary is giving error output as below :  
```
align-linux: line 1: syntax error near unexpected token `newline'
align-linux: line 1: `!<arch>'
```

**Comment by Guitarbum722** [comment]
@muralikodali thanks for reporting.  I was able to reproduce.  Can you confirm that this is occurring when you run a binary that was provided in the release?  Would you mind confirming that everything is OK when you compile and run `main.go` directly in the `cmd/align` package?

**Comment by muralikodali** [comment]
I have tried align, after cloning and compiling with make command.
I have got the same error as before as with the latest release binary.

**Comment by Guitarbum722** [comment]
@muralikodali - I'm working on this.  There's a build issue of some sort.  It seems you can try to run `build.sh` directly with `./build.sh linux` and that should get a working binary for you.  I'll have a PR up soon though.
