### ISSUE TITLE
fails to work on tab seperator

### ISSUE THREAD

**Issue by muralikodali** [Guitarbum722/align#77]
align fails to work on tab separator.

i have tried the following example : 
```
ods2tsv vat2 vat2.ods | align -s "\t" -d "&"
```

**Comment by muralikodali** [comment]
removing " " around \t solved the problem
this may be fish shell specific issue.

**Comment by Guitarbum722** [comment]
@muralikodali I also tried `$'\t'` which worked splendidly.
